import { useQuery } from '@tanstack/react-query'
import Head from 'next/head'
import { useAuthenticatedFetch } from '~/hooks/useFetch'

export default function Home() {
  const fetch = useAuthenticatedFetch()

  const { data } = useQuery({
    queryKey: ['test'],
    queryFn: async () =>
      fetch('http://localhost:8080/posts').then((r) => r.json()),
  })

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='flex min-h-screen flex-col items-center justify-center'></main>
    </>
  )
}
